import 'dart:io';
import 'package:flutter/services.dart';

import 'package:defyx_vpn/shared/providers/connection_state_provider.dart';
import 'package:defyx_vpn/shared/layout/navbar/widgets/switch_account_dialog.dart';
import 'package:defyx_vpn/modules/auth/application/branding_provider.dart';
import 'package:defyx_vpn/shared/layout/main_screen_background.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:defyx_vpn/core/data/local/vpn_data/vpn_data.dart';
import 'package:defyx_vpn/modules/auth/application/subscription_provider.dart';
import 'package:defyx_vpn/modules/auth/data/repository/auth_repository.dart';
import 'package:defyx_vpn/shared/providers/locale_provider.dart';
import 'package:defyx_vpn/shared/services/device_service.dart';
import 'package:defyx_vpn/l10n/app_localizations.dart';
import 'package:glassmorphism_ui/glassmorphism_ui.dart';
import 'package:defyx_vpn/core/theme/app_icons.dart';
import 'package:go_router/go_router.dart';

class SettingsScreen extends ConsumerStatefulWidget {
  const SettingsScreen({super.key});

  @override
  ConsumerState<SettingsScreen> createState() => _SettingsScreenState();
}

// Helper class for Settings screen localized strings
class _SettingsStrings {
  final String locale;
  _SettingsStrings(this.locale);

  String get securePrivate => _t({'en': 'Secure & Private', 'fa': 'امن و خصوصی', 'ru': 'Безопасно и приватно', 'zh': '安全私密'});
  String get accountSection => _t({'en': 'ACCOUNT', 'fa': 'حساب کاربری', 'ru': 'АККАУНТ', 'zh': '账户'});
  String get switchAccount => _t({'en': 'Switch Account', 'fa': 'تغییر حساب', 'ru': 'Сменить аккаунт', 'zh': '切换账户'});
  String get secureLogout => _t({'en': 'Secure Logout', 'fa': 'خروج امن', 'ru': 'Безопасный выход', 'zh': '安全退出'});
  String get removeDevice => _t({'en': 'Remove Device', 'fa': 'حذف دستگاه', 'ru': 'Удалить устройство', 'zh': '移除设备'});
  String get expiresLabel => _t({'en': 'Expires', 'fa': 'انقضا', 'ru': 'Истекает', 'zh': '到期'});
  String get cancel => _t({'en': 'Cancel', 'fa': 'انصراف', 'ru': 'Отмена', 'zh': '取消'});
  String get logout => _t({'en': 'Logout', 'fa': 'خروج', 'ru': 'Выход', 'zh': '退出'});
  String get remove => _t({'en': 'Remove', 'fa': 'حذف', 'ru': 'Удалить', 'zh': '删除'});
  String get secureLogoutTitle => _t({'en': 'Secure Logout?', 'fa': 'خروج امن؟', 'ru': 'Безопасный выход?', 'zh': '安全退出？'});
  String get secureLogoutDesc => _t({'en': 'This will unlink this device and INVALIDATE your current token. A new token will be generated by your provider.', 'fa': 'این کار دستگاه شما را از لینک خارج کرده و کلید فعلی را باطل می‌کند. کلید جدید توسط ارائه‌دهنده شما ایجاد خواهد شد.', 'ru': 'Это отвяжет устройство и аннулирует ваш токен. Новый токен будет сгенерирован вашим провайдером.', 'zh': '这将解除此设备的绑定并使您的令牌失效。您的提供商将生成新的令牌。'});
  String get removeDeviceTitle => _t({'en': 'Remove Device?', 'fa': 'حذف دستگاه؟', 'ru': 'Удалить устройство?', 'zh': '移除设备？'});
  String get removeDeviceStep1Desc => _t({'en': 'This will completely remove this device from your subscription. You will need to re-enter your subscription key to use this device again.', 'fa': 'این کار دستگاه شما را کاملاً از اشتراک حذف می‌کند. برای استفاده مجدد باید کلید اشتراک خود را دوباره وارد کنید.', 'ru': 'Устройство будет полностью удалено из подписки. Для повторного использования потребуется ввести ключ подписки заново.', 'zh': '这将从您的订阅中完全移除此设备。您需要重新输入订阅密钥才能再次使用此设备。'});
  String get removeDeviceStep2Title => _t({'en': 'Are you absolutely sure?', 'fa': 'آیا کاملاً مطمئن هستید؟', 'ru': 'Вы абсолютно уверены?', 'zh': '您确定要继续吗？'});
  String get removeDeviceStep2Desc => _t({'en': 'This action cannot be undone. Your access will be permanently revoked until you re-register with a valid subscription key.', 'fa': 'این عمل قابل بازگشت نیست. دسترسی شما برای همیشه لغو می‌شود تا زمانی که با کلید اشتراک معتبر دوباره ثبت‌نام کنید.', 'ru': 'Это действие необратимо. Ваш доступ будет окончательно отозван до повторной регистрации с действующим ключом.', 'zh': '此操作无法撤销。您的访问权限将被永久撤销，直到您使用有效的订阅密钥重新注册。'});
  String get dangerZone => _t({'en': 'DANGER ZONE', 'fa': 'منطقه خطر', 'ru': 'ОПАСНАЯ ЗОНА', 'zh': '危险区域'});

  String _t(Map<String, String> translations) => translations[locale] ?? translations['en']!;
}

class _SettingsScreenState extends ConsumerState<SettingsScreen> {
  @override
  Widget build(BuildContext context) {
    final connectionState = ref.watch(connectionStateProvider);
    final l10n = AppLocalizations.of(context)!;
    final s = _SettingsStrings(l10n.localeName); // Helper for new Settings translations
    final branding = ref.watch(brandingProvider);
    // Use dynamic branding on all platforms
    final appName = branding?.appName ?? 'MetaCore';

    return MainScreenBackground(
      connectionStatus: connectionState.status,
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
           backgroundColor: Colors.transparent,
           elevation: 0,
           leading: IconButton(
             icon: const Icon(Icons.arrow_back_ios_new_rounded, color: Colors.white),
             onPressed: () => Navigator.of(context).pop(),
           ),
           title: Text(
             l10n.settingsTitle, 
             style: TextStyle(color: Colors.white, fontSize: 18.sp, fontWeight: FontWeight.bold)
           ),
           centerTitle: true,
        ),
        body: SingleChildScrollView(
          padding: EdgeInsets.symmetric(horizontal: 24.w, vertical: 10.h),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // --- App Info / Branding ---
              Center(
                child: Column(
                  children: [
                    Container(
                      padding: EdgeInsets.all(16.w),
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.05),
                        shape: BoxShape.circle,
                      ),
                      child: Icon(Icons.shield_moon_rounded, size: 40.sp, color: const Color(0xFFAD7AF1)),
                    ),
                    SizedBox(height: 12.h),
                    Text(
                      appName,
                      style: TextStyle(color: Colors.white, fontSize: 20.sp, fontWeight: FontWeight.bold),
                    ),
                    Text(
                      s.securePrivate,
                      style: TextStyle(color: Colors.white54, fontSize: 12.sp),
                    ),
                  ],
                ),
              ),
              SizedBox(height: 32.h),

              // --- Account Management ---
              Text(
                s.accountSection,
                style: TextStyle(
                  color: Colors.white.withOpacity(0.5),
                  fontSize: 12.sp,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 1.5,
                ),
              ),
              SizedBox(height: 12.h),
              _buildAccountCard(ref, context, s),
              
              SizedBox(height: 32.h),
              
              // --- Danger Zone (Remove Device) ---
              Text(
                s.dangerZone,
                style: TextStyle(
                  color: Colors.redAccent.withOpacity(0.7),
                  fontSize: 12.sp,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 1.5,
                ),
              ),
              SizedBox(height: 12.h),
              _buildDangerZone(ref, context, s),
            ],
          ),
        ),
      ),
    );
  }


  Widget _buildAccountCard(WidgetRef ref, BuildContext context, _SettingsStrings s) {
    final subscriptionState = ref.watch(subscriptionProvider);
    final currentSub = subscriptionState.current;
    
    // Safety check
    if (currentSub.token == null) return const SizedBox.shrink();

    return GlassContainer(
      blur: 15,
      opacity: 0.05,
      borderRadius: BorderRadius.circular(20.r),
      border: Border.all(color: Colors.white.withOpacity(0.08)),
      child: Column(
        children: [
           // Current Subscription Info
           Padding(
             padding: EdgeInsets.all(20.w),
             child: Row(
               children: [
                 Container(
                   padding: EdgeInsets.all(12.w),
                   decoration: BoxDecoration(
                     color: const Color(0xFFAD7AF1).withOpacity(0.1),
                     shape: BoxShape.circle,
                   ),
                   child: Icon(Icons.person_rounded, color: const Color(0xFFAD7AF1), size: 24.sp),
                 ),
                 SizedBox(width: 16.w),
                 Expanded(
                   child: Column(
                     crossAxisAlignment: CrossAxisAlignment.start,
                     children: [
                       Text(
                         currentSub.name,
                         style: TextStyle(color: Colors.white, fontSize: 16.sp, fontWeight: FontWeight.bold),
                         maxLines: 1, overflow: TextOverflow.ellipsis,
                       ),
                       SizedBox(height: 4.h),
                       Text(
                         '${s.expiresLabel}: ${currentSub.expiryDate}',
                         style: TextStyle(color: Colors.white54, fontSize: 12.sp),
                       ),
                     ],
                   ),
                 ),
               ],
             ),
           ),
           Divider(color: Colors.white.withOpacity(0.05), height: 1),
           
           // Actions
           if (subscriptionState.otherSubscriptions.isNotEmpty)
             _buildActionTile(
               icon: Icons.swap_horiz_rounded,
               title: s.switchAccount,
               onTap: () {
                 showDialog(
                   context: context,
                   builder: (ctx) => const SwitchAccountDialog(),
                 );
               },
             ),
           
           if (subscriptionState.otherSubscriptions.isNotEmpty)
             Divider(color: Colors.white.withOpacity(0.05), height: 1),

             _buildActionTile(
                icon: Icons.lock_reset_rounded,
                title: s.secureLogout,
                onTap: () => _confirmSecureLogout(context, ref, currentSub.token!, s),
              ),
        ],
      ),
    );
  }

  Widget _buildDangerZone(WidgetRef ref, BuildContext context, _SettingsStrings s) {
    return GlassContainer(
      blur: 15,
      opacity: 0.05,
      borderRadius: BorderRadius.circular(20.r),
      border: Border.all(color: Colors.redAccent.withOpacity(0.2)),
      child: _buildActionTile(
        icon: Icons.phonelink_erase_rounded,
        title: s.removeDevice,
        isDestructive: true,
        onTap: () => _confirmRemoveDevice(context, ref, s),
      ),
    );
  }

  Widget _buildActionTile({required IconData icon, required String title, required VoidCallback onTap, bool isDestructive = false}) {
    return InkWell(
      onTap: onTap,
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 20.w, vertical: 16.h),
        child: Row(
          children: [
            Icon(icon, color: isDestructive ? Colors.redAccent : Colors.white70, size: 20.sp),
            SizedBox(width: 16.w),
            Text(
              title,
              style: TextStyle(
                color: isDestructive ? Colors.redAccent : Colors.white70,
                fontSize: 14.sp,
                fontWeight: FontWeight.w500,
              ),
            ),
            const Spacer(),
            Icon(Icons.arrow_forward_ios_rounded, color: Colors.white24, size: 14.sp),
          ],
        ),
      ),
    );
  }

  Future<void> _confirmSecureLogout(BuildContext context, WidgetRef ref, String token, _SettingsStrings s) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF1E1E1E),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20.r)),
        title: Text(s.secureLogoutTitle, style: TextStyle(color: Colors.white, fontSize: 18.sp, fontWeight: FontWeight.bold)),
        content: Text(
          s.secureLogoutDesc,
          style: TextStyle(color: Colors.white70, fontSize: 14.sp),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(false),
            child: Text(s.cancel, style: const TextStyle(color: Colors.white54)),
          ),
          TextButton(
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(true),
            child: Text(s.logout, style: const TextStyle(color: Color(0xFFAD7AF1), fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );

    if (confirmed != true) return;
    if (!context.mounted) return;

    _showLoading(context);

    try {
       final deviceId = await DeviceService().getDeviceId() ?? 'unknown';
       debugPrint('SECURE LOGOUT: Unlinking Device ID: $deviceId');
       
       String effectiveToken = token;
       
       // If currently using Device ID as token, try to fetch the Real Master Token
       if (token == deviceId) {
           debugPrint('SECURE LOGOUT: Token matches Device ID. Attempting to fetch Real Token...');
           final real = await ref.read(authRepositoryProvider).fetchTokenByDeviceId(deviceId);
           if (real != null && real.isNotEmpty) {
               effectiveToken = real;
               debugPrint('SECURE LOGOUT: Found Real Token. Using it.');
           } else {
               debugPrint('SECURE LOGOUT: No Real Token found. Cannot perform Token Reset.');
               // Throwing here will trigger the catch block, which now executes the fallback (deleteDevice)
               throw Exception("Cannot Secure Unlink without Master Token");
           }
       }

       final success = await ref.read(authRepositoryProvider).secureUnlink(effectiveToken, deviceId);
       
       if (context.mounted) Navigator.of(context, rootNavigator: true).pop(); // Close loading

       if (success) {
           debugPrint('SECURE LOGOUT: Success. Key invalidated.');
           // Spec says: Stop VPN, Delete Data, Go to Login.
           // We do this in the finally block via _performLogout
       } else {
           debugPrint('SECURE LOGOUT: Server returned non-200. Proceeding to force logout anyway.');
       }
       
       if (context.mounted) await _performLogout(context, ref);

    } catch (e) {
       debugPrint('SECURE LOGOUT FAILED: $e');
       debugPrint('SECURE LOGOUT: Attempting Fallback to Standard Remove Device...');
       
       try {
           final deviceId = await DeviceService().getDeviceId() ?? 'unknown';
           await ref.read(authRepositoryProvider).deleteDevice(deviceId);
           debugPrint('FALLBACK: Device Removed Successfully.');
       } catch (e2) {
           debugPrint('FALLBACK FAILED: $e2. Proceeding to local logout.');
       }

       if (context.mounted) {
         // Close loading dialog safely if it's still open
         // Check if we didn't already pop it
         if (e.toString().contains('Cannot Secure Unlink') || e.toString().contains('401')) {
            // If we threw manually or got 401, dialog might still be open if we didn't pop above
             Navigator.of(context, rootNavigator: true).pop();
         } else {
             // For safety, try pop
              try { Navigator.of(context, rootNavigator: true).pop(); } catch (_) {}
         }
         
         await _performLogout(context, ref);
       }
    }
  }

  Future<void> _confirmRemoveDevice(BuildContext context, WidgetRef ref, _SettingsStrings s) async {
    // Step 1: First confirmation
    final step1Confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF1E1E1E),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20.r)),
        title: Text(s.removeDeviceTitle, style: TextStyle(color: Colors.white, fontSize: 18.sp, fontWeight: FontWeight.bold)),
        content: Text(
          s.removeDeviceStep1Desc,
          style: TextStyle(color: Colors.white70, fontSize: 14.sp),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(false),
            child: Text(s.cancel, style: const TextStyle(color: Colors.white54)),
          ),
          TextButton(
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(true),
            child: Text(s.remove, style: const TextStyle(color: Colors.redAccent, fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );

    if (step1Confirmed != true) return;
    if (!context.mounted) return;

    // Step 2: Second confirmation (more serious warning)
    final step2Confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF2A1515),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20.r)),
        title: Row(
          children: [
            Icon(Icons.warning_amber_rounded, color: Colors.redAccent, size: 24.sp),
            SizedBox(width: 8.w),
            Expanded(child: Text(s.removeDeviceStep2Title, style: TextStyle(color: Colors.redAccent, fontSize: 18.sp, fontWeight: FontWeight.bold))),
          ],
        ),
        content: Text(
          s.removeDeviceStep2Desc,
          style: TextStyle(color: Colors.white70, fontSize: 14.sp),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(false),
            child: Text(s.cancel, style: const TextStyle(color: Colors.white54)),
          ),
          TextButton(
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(true),
            style: TextButton.styleFrom(backgroundColor: Colors.redAccent.withOpacity(0.2)),
            child: Text(s.remove, style: const TextStyle(color: Colors.redAccent, fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );

    if (step2Confirmed != true) return;
    if (!context.mounted) return;

    _showLoading(context);

    try {
       final deviceId = await DeviceService().getDeviceId() ?? 'unknown';
       debugPrint('REMOVE DEVICE: Deleting Device ID: $deviceId');
       
       await ref.read(authRepositoryProvider).deleteDevice(deviceId);
       
       if (context.mounted) {
          Navigator.of(context, rootNavigator: true).pop(); // Close loading
          await _performLogout(context, ref);
       }

    } catch (e) {
       debugPrint('REMOVE DEVICE ERROR: $e');
       if (context.mounted) {
         Navigator.of(context, rootNavigator: true).pop(); // Close loading
          // Force logout even on error to prevent stuck state
         await _performLogout(context, ref);
       }
    }
  }

  void _showLoading(BuildContext context) {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (ctx) => const Center(child: CircularProgressIndicator(color: Color(0xFFAD7AF1))),
      );
  }

  Future<void> _performLogout(BuildContext context, WidgetRef ref) async {
      debugPrint('LOGOUT: Starting cleanup...');
      try {
         final vpnData = await ref.read(vpnDataProvider.future);
         await vpnData.clearAll();
         await ref.read(authRepositoryProvider).logout();
         debugPrint('LOGOUT: Cleanup complete.');
      } catch (e) {
          debugPrint('LOGOUT ERROR: $e');
      } finally {
         // Force navigation to LOGIN, bypassing Splash to avoid re-login loops
         debugPrint('LOGOUT: Navigating to /login');
         if (context.mounted) {
           context.go('/login');
         }
      }
  }
}
