package com.devmhm.aether_client

import android.app.Activity
import android.content.Intent
import androidx.annotation.NonNull
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import io.flutter.plugin.common.PluginRegistry

// Import the Go Library (Generated by gomobile bind)
import mobile.Mobile

class AetherClientPlugin: FlutterPlugin, MethodCallHandler, ActivityAware, PluginRegistry.ActivityResultListener {
  private lateinit var channel : MethodChannel
  private var flutterPluginBinding: FlutterPlugin.FlutterPluginBinding? = null
  private var activity: Activity? = null
  private var pendingResult: Result? = null
  private var pendingConfig: String? = null

  companion object {
    private const val VPN_REQUEST_CODE = 24
  }

  override fun onAttachedToEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
    flutterPluginBinding = binding
    channel = MethodChannel(binding.binaryMessenger, "aether_client")
    channel.setMethodCallHandler(this)
  }

  override fun onAttachedToActivity(binding: ActivityPluginBinding) {
    activity = binding.activity
    binding.addActivityResultListener(this)
  }

  override fun onDetachedFromActivityForConfigChanges() {
    activity = null
  }

  override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
    activity = binding.activity
    binding.addActivityResultListener(this)
  }

  override fun onDetachedFromActivity() {
    activity = null
  }

  override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
    if (requestCode == VPN_REQUEST_CODE) {
      if (resultCode == Activity.RESULT_OK) {
        // Permission granted, start VPN service
        val config = pendingConfig ?: "{}"
        val context = flutterPluginBinding?.applicationContext ?: return false
        val serviceIntent = Intent(context, AetherVpnService::class.java)
        serviceIntent.putExtra("config", config)
        context.startForegroundService(serviceIntent)
        pendingResult?.success(null)
      } else {
        // Permission denied
        pendingResult?.error("VPN_PERMISSION_DENIED", "User denied VPN permission", null)
      }
      pendingResult = null
      pendingConfig = null
      return true
    }
    return false
  }

  override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
    when (call.method) {
      "start" -> {
        val config = call.argument<String>("config")
        if (config == null) {
          result.error("INVALID_ARGUMENT", "Config is null", null)
          return
        }
        
        val context = (flutterPluginBinding?.applicationContext) ?: return
        
        // Check VPN Permission
        val intent = android.net.VpnService.prepare(context)
        if (intent != null) {
            // Need permission - request it
            if (activity != null) {
              pendingResult = result
              pendingConfig = config
              activity?.startActivityForResult(intent, VPN_REQUEST_CODE)
            } else {
              result.error("NO_ACTIVITY", "Activity not available for permission request", null)
            }
            return
        }

        // Permission already granted
        val serviceIntent = Intent(context, AetherVpnService::class.java)
        serviceIntent.putExtra("config", config)
        context.startForegroundService(serviceIntent)
        result.success(null)
      }
      "stop" -> {
        val context = (flutterPluginBinding?.applicationContext) ?: return
        val intent = Intent(context, AetherVpnService::class.java)
        intent.action = "STOP"
        context.startService(intent)
        result.success(null)
      }
      "getStats" -> {
        val stats = Mobile.getStats()
        result.success(stats)
      }
      "request" -> {
        val endpoint = call.argument<String>("endpoint")
        val payload = call.argument<String>("payload")
        if (endpoint == null || payload == null) {
            result.error("INVALID_ARGUMENT", "Endpoint and Payload required", null)
            return
        }
        
        // Run network call on background thread
        Thread {
            val response = Mobile.request(endpoint, payload)
            // Post result back to main thread
            android.os.Handler(android.os.Looper.getMainLooper()).post {
                result.success(response)
            }
        }.start()
      }
      else -> {
        result.notImplemented()
      }
    }
  }

  override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
    channel.setMethodCallHandler(null)
  }
}
