import Flutter
import UIKit
import Aether // The framework generated by gomobile

public class SwiftAetherClientPlugin: NSObject, FlutterPlugin {
  public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(name: "aether_client", binaryMessenger: registrar.messenger())
    let instance = SwiftAetherClientPlugin()
    registrar.addMethodCallDelegate(instance, channel: channel)
  }

  public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    if call.method == "start" {
        guard let args = call.arguments as? [String: Any],
              let config = args["config"] as? String else {
            result(FlutterError(code: "INVALID_ARGUMENT", message: "Config is required", details: nil))
            return
        }
        
        var err: NSError?
        AetherStart(config, &err)
        if let err = err {
            result(FlutterError(code: "START_FAILED", message: err.localizedDescription, details: nil))
        } else {
            result(nil)
        }
        
    } else if call.method == "stop" {
        AetherStop()
        result(nil)
        
    } else if call.method == "getStats" {
        let stats = AetherGetStats()
        result(stats)
        
    } else if call.method == "request" {
        guard let args = call.arguments as? [String: Any],
              let endpoint = args["endpoint"] as? String,
              let payload = args["payload"] as? String else {
            result(FlutterError(code: "INVALID_ARGUMENT", message: "Endpoint and Payload required", details: nil))
            return
        }
        
        // Call the new AetherRequest function
        let response = AetherRequest(endpoint, payload)
        result(response)
        
    } else {
        result(FlutterMethodNotImplemented)
    }
  }
}
